// This file will be generated by Supabase CLI
// npx supabase gen types typescript --project-id "your-project-id" --schema public > src/types/supabase.ts

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      applications: {
        Row: {
          id: string;
          full_name: string;
          age: number;
          city: string;
          state: string;
          phone: string;
          email: string;
          experience: string;
          motivation: string;
          status: "new" | "in_review" | "accepted" | "rejected";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          full_name: string;
          age: number;
          city: string;
          state: string;
          phone: string;
          email: string;
          experience: string;
          motivation: string;
          status?: "new" | "in_review" | "accepted" | "rejected";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          age?: number;
          city?: string;
          state?: string;
          phone?: string;
          email?: string;
          experience?: string;
          motivation?: string;
          status?: "new" | "in_review" | "accepted" | "rejected";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};

type PublicSchema = Database[Extract<keyof Database, "public">];

export type Tables<TableName extends keyof PublicSchema["Tables"]> =
  PublicSchema["Tables"][TableName]["Row"];

export type Enums<EnumName extends keyof PublicSchema["Enums"]> =
  PublicSchema["Enums"][EnumName];